swagger: "2.0"
info:
  title: Todo Schedule API 
  version: "1"

consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Access-Token
    description: LINE token
security:
  - ApiKeyAuth: []

host: api.example.com
schemes:
  - https

paths:
  $ref: ./paths/index.yml
definitions:
  $ref: ./definitions/index.yml
